// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPdfmQRon1P-_bpls179UwiSFUSr8ZD_8',
    appId: '1:647963323687:web:1091689f2b6789d6f30d02',
    messagingSenderId: '647963323687',
    projectId: 'home-screen-bd2a8',
    authDomain: 'home-screen-bd2a8.firebaseapp.com',
    storageBucket: 'home-screen-bd2a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLVa_1TRvV-JINB7crFZskD2djbzFpYY',
    appId: '1:647963323687:android:e4afbb8eb7cec1ddf30d02',
    messagingSenderId: '647963323687',
    projectId: 'home-screen-bd2a8',
    storageBucket: 'home-screen-bd2a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPS_vL86y3bLQ-SqmXbb3oLMs0Llpz-q0',
    appId: '1:647963323687:ios:81b929ccd63cafa6f30d02',
    messagingSenderId: '647963323687',
    projectId: 'home-screen-bd2a8',
    storageBucket: 'home-screen-bd2a8.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPS_vL86y3bLQ-SqmXbb3oLMs0Llpz-q0',
    appId: '1:647963323687:ios:81b929ccd63cafa6f30d02',
    messagingSenderId: '647963323687',
    projectId: 'home-screen-bd2a8',
    storageBucket: 'home-screen-bd2a8.firebasestorage.app',
    iosBundleId: 'com.example.studyBuddyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPdfmQRon1P-_bpls179UwiSFUSr8ZD_8',
    appId: '1:647963323687:web:7b0c6d68e8989d36f30d02',
    messagingSenderId: '647963323687',
    projectId: 'home-screen-bd2a8',
    authDomain: 'home-screen-bd2a8.firebaseapp.com',
    storageBucket: 'home-screen-bd2a8.firebasestorage.app',
  );
}
